openapi: 3.0.0
info:
  version: 1.0.0
  title: Questions API
paths:
  /questions:
    get:
      summary: Get all questions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
